### ISSUE TITLE
你好，请问数据接口的API从哪里弄得，自己写的吗?

### ISSUE THREAD

**Issue by supuwoerc** [djyuning/MPOurWorldSpace#3]
还是说是第三方接口呢，自己也想做一个，但是没数据来源很苦恼

**Comment by djyuning** [comment]
目前还没写后台·····😂，业余时间练习的。

当前使用的是 [Moco](https://github.com/dreamhead/moco), 是纯手写 JSON（很 LOW 哈），因为我主要是熟悉小程序的开发套路，所以，暂时没有弄的太复杂 —— 手写JSON虽然很 LOW，但是相对灵活。

建议你使用 [koa +mock.js](https://www.jianshu.com/p/e1b7a217b5dc) 做 API。

或者直接使用[在线 API 生成工具](http://www.atool.org/httptest.php)来做模拟数据。

**Comment by supuwoerc** [comment]
感谢，没怎么学过koa，打算试试Express写一下  =。=

**Comment by djyuning** [comment]
都是可以的，顺手就可以了。
